# -*- coding: utf-8 -*-
# vim: ft=yaml
---
dist: bionic
stages:
  - test

sudo: required
cache: bundler
language: ruby

services:
  - docker

env:
  matrix:
    - INSTANCE: default-debian-10-develop-py3
    - INSTANCE: default-ubuntu-1804-2019-2-py3
    - INSTANCE: default-arch-base-latest-2019-2-py2
    - INSTANCE: default-fedora-29-2018-3-py2
    - INSTANCE: default-centos-7-2018-3-py2

script:
  - bin/kitchen verify ${INSTANCE}
